name: anyinspect
description: ""
version: 0.0.1
homepage: https://github.com/anyinspect/anyinspect

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  anyinspect_client: ^0.0.1
  device_info_plus: ^3.1.0
  network_info_plus: ^2.0.2
  package_info_plus: ^1.3.0
  shelf: ^1.1.0
  shelf_web_socket: ^1.0.1
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# dependency_overrides:
#   anyinspect_client:
#     path: ../anyinspect_client
